# Generated by Django 4.1.7 on 2023-02-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фото"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Еда"),
                            ("clothing", "Одежда"),
                            ("tech", "Техника"),
                            ("drinks", "Напитки"),
                            ("other", "Разное"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("remains", models.PositiveIntegerField(verbose_name="Остаток")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Стоимость"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удален"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
        ),
    ]
