# Generated by Django 4.1.7 on 2023-03-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_cart_created_at_cart_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(name="cart", options={},),
        migrations.AlterField(
            model_name="cart",
            name="amount",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="products",
                to="webapp.product",
                verbose_name="Продукт",
            ),
        ),
    ]
