# Generated by Django 4.1.7 on 2023-03-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_cart_options_alter_cart_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="amount", new_name="quantity",
        ),
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="webapp.product",
                verbose_name="Продукт",
            ),
        ),
    ]
