# Generated by Django 4.1.7 on 2023-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_rename_amount_cart_quantity_alter_cart_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=255, verbose_name="Имя пользователя"),
                ),
                ("phone", models.CharField(max_length=255, verbose_name="Телефон")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                ("products", models.ManyToManyField(to="webapp.product")),
            ],
        ),
    ]
