# Generated by Django 4.1.7 on 2023-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0006_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(to="webapp.product", verbose_name="Продукты"),
        ),
    ]
